apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-evermos
spec:
  acme:
    email: imam@blast.co.id
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-evermos
    solvers:
    - http01:
        ingress:
          class: nginx